build:
  image: bjodah/bjodahimg16dev:v1.3
  commands:
    - ./scripts/ci.sh pykinsol
    - (cd examples/; jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=300 *.ipynb)
    - (cd examples/; ../scripts/render_index.sh *.html)
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/grep-for-merge-blocking-token.sh
    - ./scripts/grep-for-binary-data.sh
    - apt-get remove libsundials*
    - python2 -m pip uninstall --yes pykinsol
    - python3 -m pip uninstall --yes pykinsol
    - rm -r /usr/local/lib/python*/dist-packages/pykinsol*
    - mv deploy/ /tmp/
    - git clean -xfd
    - ./scripts/.ci/download_and_install_sundials-3.1.sh
    - LD_LIBRARY_PATH=/usr/local/lib LIBRARY_PATH=/usr/local/lib CPLUS_INCLUDE_PATH=/usr/local/include PYKINSOL_SUNDIALS=3 ./scripts/ci.sh pykinsol
    - mv /tmp/deploy .

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: pykinsol
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
