pipeline:

  test-sund-5.5.0:
    group: testing
    image: bjodah/bjodahimg20dot:2.1.1.2
    environment:
      - CC=gcc-10
      - CXX=g++-10
      - OMP_NUM_THREADS=1
      - CPLUS_INCLUDE_PATH=/usr/include/suitesparse
      - LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    commands:
      - bash -c "ulimit -v 2048000; .ci/run_ci.sh pykinsol /opt/sundials-5.5.0-klu-lapack"
      - ./scripts/prepare_deploy.sh
      - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
      - ./scripts/grep-for-merge-blocking-token.sh
      - ./scripts/grep-for-binary-data.sh

  test-sund-5.5.0-noklu-nolapack-dbg-py39:
    group: testing
    image: bjodah/bjodahimg20dot:2.1.1.2
    environment:
      - CC=gcc-10
      - CXX=g++-10
      - OMP_NUM_THREADS=1
      - CPLUS_INCLUDE_PATH=/usr/include/suitesparse
      - LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      - PYTHON=python3.9
      - CFLAGS=-Werror -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
    commands:
      - export PATH="/opt/cpython-3.9-dbg/bin:$PATH"
      - bash -c "ulimit -v 2048000; PYKINSOL_NO_LAPACK=1 PYKINSOL_NO_KLU=1 .ci/run_ci.sh pykinsol /opt/sundials-5.5.0-noklu-nolapack-dbg"

  test-sund-5.5.0-asan:
    group: testing
    image: bjodah/bjodahimg20dot:2.1.1.2
    environment:
      - CPATH=/usr/include/suitesparse
      - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-11/bin/llvm-symbolizer
      - ASAN_OPTIONS=symbolize=1,detect_leaks=0
      - CC=clang-11
      - CXX=clang++-11
      - CFLAGS=-fsanitize=address -g -fno-omit-frame-pointer -fsized-deallocation
      - PY_LD_PRELOAD=/usr/lib/llvm-11/lib/clang/11.0.1/lib/linux/libclang_rt.asan-x86_64.so
    commands:
      - bash -c ".ci/run_ci.sh pykinsol /opt/sundials-5.5.0-klu-lapack"

deploy:

  deploy:
    image: drillster/drone-rsync
    when:
      event: [push]
    hosts: [ "hera.physchem.kth.se" ]
    port: 22
    user: pykinsol
    secrets: [ rsync_key ]  # secret only set from event "push" not "pull_request"
    source: ./deploy/public_html
    target: ~/
